name: CI Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      - name: Install dependencies
        run: go mod download

      - name: Build the application
        run: go build -v

      - name: Run tests
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t golang-api-image:latest .

      - name: Stop and Remove Existing Container
        run: |
          docker ps -q -f name=golang-api | ForEach-Object { docker stop $_ }
          docker ps -aq -f name=golang-api | ForEach-Object { docker rm $_ }

      - name: Run Docker container
        run: |
          docker run -d --name golang-api -p 8000:8000 `
            -e APP_PORT=8000 `
            -e USE_MODSIM=true `
            -e MACHINE_1_IP=192.168.1.33 `
            -e MACHINE_1_PORT=501 `
            -e MACHINE_1_START_ADDRESS=100 `
            -e MACHINE_1_READ_COUNT=10 `
            -e MACHINE_2_IP=192.168.1.33 `
            -e MACHINE_2_PORT=502 `
            -e MACHINE_2_START_ADDRESS=100 `
            -e MACHINE_2_READ_COUNT=10 `
           golang-api-image:latest
          
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker tag golang-api-image:latest ${{ secrets.DOCKER_USERNAME }}/golang-api-image:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/golang-api-image:latest
          